### ISSUE TITLE
Jackett host is invalid

### ISSUE THREAD

**Issue by chicungunya** [fugkco/script.elementum.jackett#2] opened 2020-05-26 12:23 UTC
Hi @fugkco ,
I just tried your addon but it's not working. 
Just FYI, I use Jackett on a raspberry pi with this IP : XXX.XXX.X.12 and elementum is on my android TV with this IP XXX.XXX.X.3.

This is my log : http://paste.kodi.tv/urajiwetol

Thansk a lot !

**Comment by fugkco** [comment] 2020-05-26 12:43
I've uploaded a new version that includes some improvements. Can you try and if it doesn't work make sure you enable debug logging when uploading the logs.

**Comment by chicungunya** [comment] 2020-05-26 12:48
Still not; I enabled debug in Elementum Jackett : http://paste.kodi.tv/anaworugow

**Comment by fugkco** [comment] 2020-05-26 13:07
So if the configuration looks correct, there will be debug entries in the log with a partial api key and the full url it will attempt to connect to. I don't see either of those. Can you confirm you've set the host and apikey correctly? Then also click the validate settings option in the settings.

**Comment by chicungunya** [comment] 2020-05-26 13:15
Ok so this is my kodi.log : https://pastebin.com/eCV9hHRn
My api key and the host are corrects.
When I click on Validate settings, I have the error : Jackett host is invalid

**Comment by fugkco** [comment] 2020-05-26 13:25
The host has to be in the format: `http://<ip>:<port>`

**Comment by fugkco** [comment] 2020-05-26 13:25
Can you post a screenshot of the settings menu?

**Comment by chicungunya** [comment] 2020-05-26 13:42
My bad I forgot http://
Ok so now script is working, I can validate my settings.
But I have errors in results : https://pastebin.com/dAgZAWAN
I think there are multiples errors because of accent in movie name or specific character.
Do you need that I open a new issue or we can keep going here ?

**Comment by fugkco** [comment] 2020-05-26 21:57
Nope this looks like misconfiguration of Jackett. No results are being returned by Jackett.

Can you post the output of the following:
```
curl -s 'http://<HOST>:<PORT>/api/v2.0/indexers/all/results/torznab?t=caps&apikey=<APIKEY>' | grep supported
```

and also

```
curl -s 'http://<HOST>:<PORT>/api/v2.0/indexers/all/results/torznab?t=movie&apikey=<APIKEY>&imdbid=tt8767908'
```

Replace `<HOST>`, `<PORT>`, and `<APIKEY>` with the relevant values first.

**Comment by fugkco** [comment] 2020-05-26 21:58
Also, which indexers have you configured in Jackett?

**Comment by chicungunya** [comment] 2020-05-27 11:04
> `curl -s 'http://<HOST>:<PORT>/api/v2.0/indexers/all/results/torznab?t=caps&apikey=<APIKEY>' | grep supported`

    `<search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season,ep" />
    <movie-search available="yes" supportedParams="q,imdbid" />
    <music-search available="no" supportedParams="" />
    <audio-search available="no" supportedParams="" />`

> `curl -s 'http://<HOST>:<PORT>/api/v2.0/indexers/all/results/torznab?t=movie&apikey=<APIKEY>&imdbid=tt8767908'`

`<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://192.168.1.12:9117/" rel="self" type="application/rss+xml" />
    <title>AggregateSearch</title>
    <description>This feed includes all configured trackers</description>
    <link>http://127.0.0.1/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://192.168.1.12:9117/logos/all.png</url>
      <title>AggregateSearch</title>
      <link>http://127.0.0.1/</link>
      <description>AggregateSearch</description>
    </image>
  </channel>
</rss>`

> Also, which indexers have you configured in Jackett?

YGGCookie (Semi-Private), IPTorrents (Private), Elite-Tracker (Private), Torrentleech (Private)


My last log : https://paste.kodi.tv/ohawusafat.kodi
For example, for the movie Brooklyn Affaires, I don't have any results in elementum but in the log I can see it finds some links on Jackett

**Comment by fugkco** [comment] 2020-05-27 23:13
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://192.168.1.12:9117/" rel="self" type="application/rss+xml" />
    <title>AggregateSearch</title>
    <description>This feed includes all configured trackers</description>
    <link>http://127.0.0.1/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://192.168.1.12:9117/logos/all.png</url>
      <title>AggregateSearch</title>
      <link>http://127.0.0.1/</link>
      <description>AggregateSearch</description>
    </image>
  </channel>
</rss>
```

The first one is a Jackett issue, it's not returning any results. The plugin can't do anything if it doesn't get data from Jackett.

Regarding the results in the logs, there's definitely results being returned from Jackett. I've uploaded a new version with some additional logging, if you can please install that and rerun it with debug on and upload the logs.

**Comment by chicungunya** [comment] 2020-05-28 11:13
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
>   <channel>
>     <atom:link href="http://192.168.1.12:9117/" rel="self" type="application/rss+xml" />
>     <title>AggregateSearch</title>
>     <description>This feed includes all configured trackers</description>
>     <link>http://127.0.0.1/</link>
>     <language>en-us</language>
>     <category>search</category>
>     <image>
>       <url>http://192.168.1.12:9117/logos/all.png</url>
>       <title>AggregateSearch</title>
>       <link>http://127.0.0.1/</link>
>       <description>AggregateSearch</description>
>     </image>
>   </channel>
> </rss>
> ```
> 
> The first one is a Jackett issue, it's not returning any results. The plugin can't do anything if it doesn't get data from Jackett.
> 
> Regarding the results in the logs, there's definitely results being returned from Jackett. I've uploaded a new version with some additional logging, if you can please install that and rerun it with debug on and upload the logs.

Voila : https://paste.kodi.tv/conegaraki.kodi

**Comment by fugkco** [comment] 2020-05-28 12:30
Very interesting. I see what the issue is! I've added a fix to 0.0.5. Please try that.

**Comment by chicungunya** [comment] 2020-05-28 12:43
Right here : https://paste.kodi.tv/ifewomokay.kodi

**Comment by fugkco** [comment] 2020-05-28 21:16
Added more logging, if you can try the one attached please.

[script.elementum.jackett.zip](https://github.com/fugkco/script.elementum.jackett/files/4698309/script.elementum.jackett.zip)

**Comment by chicungunya** [comment] 2020-05-28 23:14
Right here : https://paste.kodi.tv/sutuvimivi.kodi :)

**Comment by fugkco** [comment] 2020-05-29 10:09
Try this one
[script.elementum.jackett.zip](https://github.com/fugkco/script.elementum.jackett/files/4701094/script.elementum.jackett.zip)

**Comment by chicungunya** [comment] 2020-05-29 10:28
https://paste.kodi.tv/xeyaviqero.kodi

**Comment by fugkco** [comment] 2020-05-29 10:36
Are you able to send me an invite to one of those trackers so I can debug this? This back and forth is not easy. Seems most results are from torrentleech, so that would be best.

**Comment by chicungunya** [comment] 2020-05-29 10:41
> Are you able to send me an invite to one of those trackers so I can debug this? This back and forth is not easy. Seems most results are from torrentleech, so that would be best.

Yes, better to speak in private ? How can we do that ?

**Comment by fugkco** [comment] 2020-05-29 11:30
`fugkco -at- protonmail[.]com`

replace `-at`- and `[.]` obviously

**Comment by fugkco** [comment] 2020-05-29 17:44
So I think I've figured it out, but please note, it's a bit of hit an miss. Torrentleech seems to have many torrents that are actually archived, meaning it will find the magnets, but Elementum may or may not be able to load the URL, though it will warn you that it's an archive.

[script.elementum.jackett.zip](https://github.com/fugkco/script.elementum.jackett/files/4703371/script.elementum.jackett.zip)

**Comment by chicungunya** [comment] 2020-05-29 17:59
With my SOCKS5 Proxy : https://paste.kodi.tv/fatapexice.kodi

Still not results on Elementum

Do you want I try without TorrentLeech ? 

Thanks

**Comment by chicungunya** [comment] 2020-05-29 18:16
Ok it works without TorrentLeech but I don't have results from YGG.
I tried YGG alone on Jackett and it's working but with the others, no results from YGG.
My logs : https://paste.kodi.tv/vuwexuxabo.kodi

**Comment by chicungunya** [comment] 2020-05-29 18:30
Ok only IPtorrents with YGG : https://paste.kodi.tv/kududibufo.kodi
Only results from Iptorrents

**Comment by chicungunya** [comment] 2020-05-29 18:42
Ok so stream works with IPTorrents and Elite-tracker but not with YGG : https://paste.kodi.tv/upakubeham.kodi
Do you think it's a problem with Elementum @elgatito ?

**Comment by elgatito** [comment] 2020-05-29 19:44
@chicungunya 

```
2020-05-29 14:41:59.214 T:5250   DEBUG: [script.elementum.jackett] All results: [{'info_hash': '', '_resolution': '1080p', 'icon': u'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.elementum.jackett/resources/images/icon.png', 'peers': 8, '_size_bytes': 6023691776L, 'name': u'Delire Express Unrated (2008) Multi 720P BluRay x264.mkv', 'language': None, 'uri': 'magnet:?xt=urn:btih:b1a62ea5e02907a8aaa9bdd390d17f91f131b648&tr=http%3A%2F%2Fygg.peer2peer.cc%3A8080%2FKLNumAERgHho9JQxATWL6YMlH1D9k8nU%2Fannounce', 'seeds': 8, 'provider': u'YGGtorrent', 'size': '5.61 GB', 'resolution': 4, 'release_type': 'brrip'}, {'info_hash': '', '_resolution': 'unknown', 'icon': u'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.elementum.jackett/resources/images/icon.png', 'peers': 4, '_size_bytes': 572113536, 'name': u'Delire Express.2008.French.Web-DL.x264', 'language': None, 'uri': 'magnet:?xt=urn:btih:4dbe57a4675f97ba083eaa01b008dd33dfa64fb5&tr=http%3A%2F%2Fygg.peer2peer.cc%3A8080%2FKLNumAERgHho9JQxATWL6YMlH1D9k8nU%2Fannounce', 'seeds': 4, 'provider': u'YGGtorrent', 'size': '545.61 MB', 'resolution': 0, 'release_type': 'webdl'}]
```

Jackett returns torrent as magnet link? 
Ygg is probably having private torrents, that cannot be resolved by magnets?

You can try to add magnet to torrent client and see if it works there.

**Comment by chicungunya** [comment] 2020-05-29 19:56
> magnet:?xt=urn:btih:4dbe57a4675f97ba083eaa01b008dd33dfa64fb5&tr=http%3A%2F%2Fygg.peer2peer.cc%3A8080%2FKLNumAERgHho9JQxATWL6YMlH1D9k8nU%2Fannounce

It works when I add this magnet to torrent client (utorrent) `magnet:?xt=urn:btih:4dbe57a4675f97ba083eaa01b008dd33dfa64fb5&tr=http%3A%2F%2Fygg.peer2peer.cc%3A8080%2FKLNumAERgHho9JQxATWL6YMlH1D9k8nU%2Fannounce`

**Comment by elgatito** [comment] 2020-05-29 19:58
@chicungunya then you can try to increase magnet resolve timeout, maybe it takes a lot of time to find information.

**Comment by elgatito** [comment] 2020-05-29 20:12
I have tried this magnet on my elementum and it worked fine, so try to increase the timeout, who knows.

**Comment by fugkco** [comment] 2020-05-29 20:15
> Jackett returns torrent as magnet link?

Not necessarily. I noticed (or so I thought) for some reason sometimes when non-magnet links are returned by Jackett, Elementum would fail. No error or anything if I remember correctly. So I added some code to manually resolve the magnet before sending it to Elementum. The reason I thought this was the issue is because when I manually resolved the magnet and added it to Elementum, it worked fine. Admittedly, I didn't test out pasting the proxied link directly into Elementum.

>  Ygg is probably having private torrents, that cannot be resolved by magnets?

Wouldn't have thought torrents have any special ways of having "private" torrents in the protocol, or am I mistaken?

@chicungunya That torrent works for me too.

**Comment by chicungunya** [comment] 2020-05-29 20:26
@fugkco torrent is not working from the results  : https://streamable.com/y3z5f9
With Add file, URL on Elementum, yes it works.
Log : https://paste.kodi.tv/onuzevugel.kodi

**Comment by fugkco** [comment] 2020-05-29 20:32
> 2020-05-29 16:21:45.508 T:12074  NOTICE: [plugin.video.elementum] [31mERRO  bittorrent   ▶ WaitForMetadata  [0mExpired timeout for resolving magnet link

What's your timeout currently set to, and did you try increasing the timeout? Really odd it works when adding manually though. Anyway, Elementum is receiving the magnet uri correctly, and tries to resolve it. The issue is the timeout.

**Comment by chicungunya** [comment] 2020-05-30 11:51
> > 2020-05-29 16:21:45.508 T:12074  NOTICE: [plugin.video.elementum] �[31mERRO  bittorrent   ▶ WaitForMetadata  �[0mExpired timeout for resolving magnet link
> 
> What's your timeout currently set to, and did you try increasing the timeout? Really odd it works when adding manually though. Anyway, Elementum is receiving the magnet uri correctly, and tries to resolve it. The issue is the timeout.

Ok so I was in 60s timeout, I increased to 600 in bittorrent settings, + General setting time out to 90s, still a problem : https://paste.kodi.tv/zifoneguxu.kodi

**Comment by elgatito** [comment] 2020-05-30 11:56
```
2020-05-30 07:41:25.677 T:3924  NOTICE: [plugin.video.elementum]   MagnetResolveTimeout: 15,

```

You should increase Magnet resolve timeout. Not other timeouts.

**Comment by chicungunya** [comment] 2020-05-30 12:03
> ```
> 2020-05-30 07:41:25.677 T:3924  NOTICE: [plugin.video.elementum]   MagnetResolveTimeout: 15,
> ```
> 
> You should increase Magnet resolve timeout. Not other timeouts.

Thanks it works !

**Comment by chicungunya** [comment] 2020-05-30 12:07
> Ok only IPtorrents with YGG : https://paste.kodi.tv/kududibufo.kodi
> Only results from Iptorrents

What about this @fugkco ? It's like YGG doesn't exist anymore when I add IPtorrents on Jackett : https://paste.kodi.tv/pukaxekexa.kodi How can I get a mix of results of this both trackers ? 
Thanks a lot btw, you ve made it! 
@elgatito Thanks for your patience too !
@hoshsadiq try this script ;)

**Comment by chicungunya** [comment] 2020-05-30 15:23
@fugkco I have problem for some movies name : https://paste.kodi.tv/obijifawuz.kodi

**Comment by fugkco** [comment] 2020-05-30 22:20
So think this is a bug when the movie search only supports query search. It only searches for `$title`, in reality, it should be searching for `$title $year`. I will push a fix in the next couple of days. Meantime, in Jackett, if you add a torrent indexer that supports imdbid, it should produce the right results. From the logs, it looks like you haven't added any indexers that supports imdb searches.

**Comment by fugkco** [comment] 2020-05-30 22:21
Thanks for testing this by the way @chicungunya. I've been using pretty vanilla setup that didn't produce half of the issues you've found. Hopefully this plugin can be released to the masses soon :)

**Comment by fugkco** [comment] 2020-05-30 22:24
@elgatito do you think it's worth keeping this code https://github.com/fugkco/script.elementum.jackett/blob/master/src/client.py#L303-L324? If I remove it, would Elementum be able to properly handle non-magnet URLs that get returned by Jackett?

**Comment by chicungunya** [comment] 2020-05-31 15:22
@elgatito @fugkco is that normal with my SOCKS5 (nordvpn) and 180s timeout magnet resolve, it does'nt work sometimes ? https://paste.kodi.tv/ujexopiwoh.kodi
Thanks

**Comment by elgatito** [comment] 2020-05-31 15:29
@fugkco I would stay with magnets. Downloading a torrent file can be a problem.

**Closed as completed** 2020-08-16 14:52 UTC

**Comment by fugkco** [comment] 2020-08-16 15:21
Forgot to reply back here. Thanks @elgatito 

@chicungunya is the addon fully working for you now?

**Comment by chicungunya** [comment] 2020-08-16 15:23
@fugkco yep but I use only 2 providers (ygg torrent and iptorrents) because torrentleech doesn't work but it's ok it's enough for my use! Thanks a lot for your job !
